NDefines.NGame.START_DATE = "2014.1.1.1"
NDefines.NGame.END_DATE = "2020.1.1.1"

NDefines.NDiplomacy.OPINION_PER_VOLUNTEER = 5
NDefines.NDiplomacy.MAX_OPINION_FROM_VOLUNTEERS = 50
NDefines.NDiplomacy.BASE_IMPROVE_RELATION_COST = 25
NDefines.NTrade.RELATION_TRADE_FACTOR = 1.5

NDefines.NOperatives.DIPLOMATIC_PRESSURE_MAX_AI_ACCEPTANCE_SCORE_INCREASE = 50
NDefines.NOperatives.CONTROL_TRADE_STACKING_FACTOR = 0.7

NDefines.NCountry.MAX_PROPAGANDA_STABILITY_IMPACT = -0.6
NDefines.NCountry.MAX_PROPAGANDA_WAR_SUPPORT_IMPACT = -0.6
