NDefines.NAir.STRATEGIC_BOMBER_NUKE_AIR_SUPERIORITY = 1.1
NDefines.NMilitary.NUKE_MIN_DAMAGE_PERCENT = 0.6
NDefines.NMilitary.NUKE_MAX_DAMAGE_PERCENT = 0.9
NDefines.NMilitary.NUCLEAR_PRODUCTION_SCALE = 0.0
NDefines.NMilitary.NUKE_DELAY_HOURS = 0