NDefines.NDiplomacy.GUARANTEE_COST = 50
NDefines.NDiplomacy.TENSION_GUARANTEE = -20
NDefines.NDiplomacy.WARGOAL_THREAT_MAX_TIME_RATIO = 1
NDefines.NDiplomacy.WARGOAL_JUSTIFY_TENSION_FROM_PRODUCTION = 18