NDefines.NDiplomacy.BASE_CONDITIONAL_PEACE_WARESCORE_RATIO = 1000
NDefines.NDiplomacy.BASE_CONDITIONAL_PEACE_MONTHS = 1000

NDefines.NMilitary.ATTRITION_EQUIPMENT_LOSS_CHANCE = 0.06
NDefines.NMilitary.ATTRITION_EQUIPMENT_PER_TYPE_LOSS_CHANCE = 0.06